-- SQL Script for RogersInvoice-Spire Module Tables
-- Replicates MS Access tables in SQL Server under bvactivations database

-- 1. tblRogersInvoiceSalesTaxes (Replicates tblSalesTaxes)
IF OBJECT_ID('tblRogersInvoiceSalesTaxes', 'U') IS NULL
BEGIN
    CREATE TABLE tblRogersInvoiceSalesTaxes (
        S_TAX_NO NUMERIC(18,0) PRIMARY KEY,
        NAME VARCHAR(255),
        RATE FLOAT,
        GL_ACCOUNT VARCHAR(255),
        CreatedBy INT NULL,
        CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
        ModifiedBy INT NULL,
        ModifiedDate DATETIME NULL
    );
END;

-- 2. tblRogersInvoiceOutputData (Replicates OutputData)
IF OBJECT_ID('tblRogersInvoiceOutputData', 'U') IS NULL
BEGIN
    CREATE TABLE tblRogersInvoiceOutputData (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        UserId INT NOT NULL,
        ChannelName VARCHAR(255) NULL,
        PaymentMethod VARCHAR(255) NULL,
        Type VARCHAR(255) NULL,
        Type2 VARCHAR(255) NULL,
        Invoice VARCHAR(50) NULL,
        BVLineNo INT NULL,
        InvoiceDate DATETIME NULL,
        OrderDate DATETIME NULL,
        CustName VARCHAR(255) NULL,
        CustTerritory VARCHAR(50) NULL,
        DealerCode VARCHAR(255) NULL,
        MSD VARCHAR(255) NULL,
        UserName VARCHAR(50) NULL,
        CellPhoneNo VARCHAR(255) NULL,
        PortedCTN VARCHAR(255) NULL,
        VoicePlan VARCHAR(255) NULL,
        DataPlan VARCHAR(255) NULL,
        WebOrderID VARCHAR(255) NULL,
        Qty FLOAT NULL,
        PartNumber VARCHAR(50) NULL,
        FreeAccessory VARCHAR(255) NULL,
        IMEIESN VARCHAR(255) NULL,
        CostPrice FLOAT NULL,
        SellPrice FLOAT NULL,
        TopUpOwing FLOAT NULL,
        TopUpSDFAccCostAdjusted FLOAT NULL,
        TopUpTotal FLOAT NULL,
        AccessoryCost FLOAT NULL,
        AccessoryPrice FLOAT NULL,
        Fee FLOAT NULL,
        FeeCount FLOAT NULL,
        ARAmount FLOAT NULL,
        AdjustmentType VARCHAR(50) NULL,
        AccCurrentCostTotal FLOAT NULL,
        AccSRPTotal FLOAT NULL,
        AccSRP17Total FLOAT NULL,
        AccSRP25Total FLOAT NULL,
        AccSRP50Total FLOAT NULL,
        AccCurrentCostDetails VARCHAR(255) NULL,
        AccSRPDetails VARCHAR(255) NULL,
        AccSRP17Details VARCHAR(255) NULL,
        AccSRP25Details VARCHAR(255) NULL,
        AccSRP50Details VARCHAR(255) NULL,
        FreeAccessoryPart VARCHAR(255) NULL,
        AccSellingPriceTotal FLOAT NULL,
        ACCSellingPriceDetails VARCHAR(255) NULL,
        Province VARCHAR(50) NULL,
        BVARAmount FLOAT NULL,
        HDWSRP FLOAT NULL,
        SCOA VARCHAR(50) NULL,
        InvoiceNet DECIMAL(18,2) NULL,
        InvoiceShipping DECIMAL(18,2) NULL,
        InvoiceTaxes DECIMAL(18,2) NULL,
        InvoiceTotal DECIMAL(18,2) NULL,
        ShipToProvince VARCHAR(10) NULL,
        ACCQtys VARCHAR(255) NULL,
        M2MOrderID VARCHAR(255) NULL,
        TaxCode1 INT NULL,
        TaxCode2 INT NULL,
        BVReceiptCost DECIMAL(18,2) NULL,
        NetIMEIReceiveCost DECIMAL(18,2) NULL,
        NetPriceProtection DECIMAL(18,2) NULL,
        ReturnClassification VARCHAR(255) NULL,
        GSTRate FLOAT NULL,
        PSTRate FLOAT NULL,
        UpFrontEdgePrice DECIMAL(18,2) NULL,
        ClaimCarrier VARCHAR(255) NULL,
        ClaimNumber VARCHAR(255) NULL,
        AROutstanding DECIMAL(18,2) NULL,
        OriginalInvoice VARCHAR(255) NULL,
        DeviceOfferTypeID INT NULL,
        TaxFlag1 VARCHAR(255) NULL,
        TaxFlag2 VARCHAR(255) NULL,
        AccountNumber VARCHAR(255) NULL,
        AgentName VARCHAR(255) NULL,
        AgentEmail VARCHAR(255) NULL,
        AgentContactNumber VARCHAR(255) NULL,
        RogersHWMarginShare DECIMAL(18,2) NULL,
        Term VARCHAR(255) NULL,
        RDType VARCHAR(255) NULL,
        PPOverpayment DECIMAL(18,2) NULL,
        CreatedBy INT NULL,
        CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
        ModifiedBy INT NULL,
        ModifiedDate DATETIME NULL
    );
    CREATE INDEX IX_tblRogersInvoiceOutputData_UserId ON tblRogersInvoiceOutputData(UserId);
END;

-- 3. tblRogersInvoiceAcquisitionDetail (Replicates tblAcquisitionDetail)
IF OBJECT_ID('tblRogersInvoiceAcquisitionDetail', 'U') IS NULL
BEGIN
    CREATE TABLE tblRogersInvoiceAcquisitionDetail (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        UserId INT NOT NULL,
        ChannelName VARCHAR(255) NULL,
        PaymentMethod VARCHAR(255) NULL,
        Type VARCHAR(255) NULL,
        Invoice VARCHAR(50) NULL,
        BVLineNo INT NULL,
        RecNoDetail INT NULL,
        InvoiceDate DATETIME NULL,
        OrderDate DATETIME NULL,
        CustName VARCHAR(255) NULL,
        CustTerritory VARCHAR(50) NULL,
        DealerCode VARCHAR(255) NULL,
        CellPhoneNo VARCHAR(255) NULL,
        WebOrderID VARCHAR(255) NULL,
        Type2 VARCHAR(255) NULL,
        FreeAccessory VARCHAR(255) NULL,
        [Topup Acc] FLOAT NULL,
        AccessoryCost FLOAT NULL,
        AccessoryPrice FLOAT NULL,
        AccCurrentCostTotal FLOAT NULL,
        AccSRPTotal FLOAT NULL,
        AccSRP17Total FLOAT NULL,
        AccSRP25Total FLOAT NULL,
        AccSRP50Total FLOAT NULL,
        ACCSellingPrice FLOAT NULL,
        CODE VARCHAR(50) NULL,
        Description VARCHAR(255) NULL,
        ProdCode VARCHAR(50) NULL,
        Qty FLOAT NULL,
        BVCost FLOAT NULL,
        BVCostExt FLOAT NULL,
        BVPrice FLOAT NULL,
        BVPriceExt FLOAT NULL,
        TopUpAmt FLOAT NULL,
        TopUpOrig FLOAT NULL,
        TopUpModify VARCHAR(10) NULL,
        CustPayExt FLOAT NULL,
        AccGroup VARCHAR(50) NULL,
        Margin VARCHAR(255) NULL,
        AccSRP FLOAT NULL,
        AccSRP17 FLOAT NULL,
        AccSRP25 FLOAT NULL,
        AccSRP50 FLOAT NULL,
        TopUpRecalc FLOAT NULL,
        MSD VARCHAR(255) NULL,
        UserName VARCHAR(255) NULL,
        VoicePlan VARCHAR(255) NULL,
        DataPlan VARCHAR(255) NULL,
        GSTRate FLOAT NULL,
        PSTRate FLOAT NULL,
        Fee FLOAT NULL,
        FeePayback FLOAT NULL,
        M2MOrderID VARCHAR(255) NULL,
        ReturnClassification VARCHAR(255) NULL,
        GSTFlag VARCHAR(255) NULL,
        PSTFlag VARCHAR(255) NULL,
        AdjustmentType VARCHAR(255) NULL,
        BVReceiptNo VARCHAR(255) NULL,
        BVReceiptNoInt INT NULL,
        BVReceiptQty INT NULL,
        BVReceiptCost FLOAT NULL,
        BVReceiptDate DATETIME NULL,
        RogersInvoiceCost FLOAT NULL,
        DeviceOfferTypeID INT NULL,
        ShipToProvince VARCHAR(255) NULL,
        OriginalInvoice VARCHAR(255) NULL,
        RDAccUnitCost FLOAT NULL,
        AccessoryType VARCHAR(255) NULL,
        RogersACCMarginShare DECIMAL(18,2) NULL,
        AccountNumber VARCHAR(255) NULL,
        AgentName VARCHAR(255) NULL,
        AgentEmail VARCHAR(255) NULL,
        AgentContactNumber VARCHAR(255) NULL,
        RDType VARCHAR(255) NULL,
        CreatedBy INT NULL,
        CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
        ModifiedBy INT NULL,
        ModifiedDate DATETIME NULL
    );
    CREATE INDEX IX_tblRogersInvoiceAcquisitionDetail_UserId ON tblRogersInvoiceAcquisitionDetail(UserId);
END;

-- 4. tblRogersInvoiceAcquisitionAR (Replicates tblAcquisitionAR)
IF OBJECT_ID('tblRogersInvoiceAcquisitionAR', 'U') IS NULL
BEGIN
    CREATE TABLE tblRogersInvoiceAcquisitionAR (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        UserId INT NOT NULL,
        ChannelName VARCHAR(255) NULL,
        PaymentMethod VARCHAR(255) NULL,
        Type VARCHAR(255) NULL,
        Invoice VARCHAR(50) NULL,
        InvoiceDate DATETIME NULL,
        OrderDate DATETIME NULL,
        CustName VARCHAR(255) NULL,
        CustTerritory VARCHAR(50) NULL,
        DealerCode VARCHAR(255) NULL,
        MSD VARCHAR(255) NULL,
        UserName VARCHAR(50) NULL,
        CellPhoneNo VARCHAR(255) NULL,
        PortedCTN VARCHAR(255) NULL,
        VoicePlan VARCHAR(255) NULL,
        DataPlan VARCHAR(255) NULL,
        WebOrderID VARCHAR(255) NULL,
        Type2 VARCHAR(255) NULL,
        Qty FLOAT NULL,
        PartNumber VARCHAR(50) NULL,
        FreeAccessory VARCHAR(255) NULL,
        IMEIESN VARCHAR(255) NULL,
        CostPrice FLOAT NULL,
        SellPrice FLOAT NULL,
        TopUpOwing FLOAT NULL,
        [Topup Acc] FLOAT NULL,
        TopUpTotal FLOAT NULL,
        AccessoryPrice FLOAT NULL,
        Fee FLOAT NULL,
        FeeCount INT NULL,
        GST FLOAT NULL,
        PST FLOAT NULL,
        HST FLOAT NULL,
        QST FLOAT NULL,
        ARAmount FLOAT NULL,
        HDWChargeToCustomer DECIMAL(18,2) NULL,
        [True HDW TopUp] VARCHAR(255) NULL,
        SCOA VARCHAR(50) NULL,
        ShipToProvince VARCHAR(10) NULL,
        CreatedBy INT NULL,
        CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
        ModifiedBy INT NULL,
        ModifiedDate DATETIME NULL
    );
    CREATE INDEX IX_tblRogersInvoiceAcquisitionAR_UserId ON tblRogersInvoiceAcquisitionAR(UserId);
END;

-- 5. tblRogersInvoiceRecentReceipts (Replicates tblRecentReceipts)
IF OBJECT_ID('tblRogersInvoiceRecentReceipts', 'U') IS NULL
BEGIN
    CREATE TABLE tblRogersInvoiceRecentReceipts (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        UserId INT NOT NULL,
        PartNumber VARCHAR(255) NULL,
        ReceiptDate1 DATETIME NULL, Qty1 INT NULL, Cost1 FLOAT NULL, Invoice1 VARCHAR(255) NULL,
        ReceiptDate2 DATETIME NULL, Qty2 INT NULL, Cost2 FLOAT NULL, Invoice2 VARCHAR(255) NULL,
        ReceiptDate3 DATETIME NULL, Qty3 INT NULL, Cost3 FLOAT NULL, Invoice3 VARCHAR(255) NULL,
        ReceiptDate4 DATETIME NULL, Qty4 INT NULL, Cost4 FLOAT NULL, Invoice4 VARCHAR(255) NULL,
        ReceiptDate5 DATETIME NULL, Qty5 INT NULL, Cost5 FLOAT NULL, Invoice5 VARCHAR(255) NULL,
        ReceiptDate6 DATETIME NULL, Qty6 INT NULL, Cost6 FLOAT NULL, Invoice6 VARCHAR(255) NULL,
        ReceiptDate7 DATETIME NULL, Qty7 INT NULL, Cost7 FLOAT NULL, Invoice7 VARCHAR(255) NULL,
        CreatedBy INT NULL,
        CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
        ModifiedBy INT NULL,
        ModifiedDate DATETIME NULL
    );
    CREATE INDEX IX_tblRogersInvoiceRecentReceipts_UserId ON tblRogersInvoiceRecentReceipts(UserId);
    CREATE INDEX IX_tblRogersInvoiceRecentReceipts_PartNumber ON tblRogersInvoiceRecentReceipts(PartNumber);
END;

-- 6. tblRogersInvoiceUPSLost (Replicates tblUPSLost)
IF OBJECT_ID('tblRogersInvoiceUPSLost', 'U') IS NULL
BEGIN
    CREATE TABLE tblRogersInvoiceUPSLost (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        UserId INT NOT NULL,
        Invoice VARCHAR(50) NULL,
        InvoiceDate DATETIME NULL,
        OrderDate DATETIME NULL,
        OriginalInvoice VARCHAR(255) NULL,
        CustName VARCHAR(255) NULL,
        Territory VARCHAR(255) NULL,
        WebOrderID VARCHAR(255) NULL,
        CellPhoneNo VARCHAR(255) NULL,
        Qty FLOAT NULL,
        PartNumber VARCHAR(50) NULL,
        FreeAccessory VARCHAR(255) NULL,
        IMEIESN VARCHAR(255) NULL,
        CostPrice FLOAT NULL,
        AccessoryCost FLOAT NULL,
        TotalBeforeTaxes FLOAT NULL,
        HST FLOAT NULL,
        TotalClaim FLOAT NULL,
        Courier VARCHAR(255) NULL,
        Claim VARCHAR(255) NULL,
        [Group] VARCHAR(255) NULL,
        OutstandingAR DECIMAL(18,2) NULL,
        NetIMEIReceiveCost DECIMAL(18,2) NULL,
        NetPriceProtection DECIMAL(18,2) NULL,
        NetCost DECIMAL(18,2) NULL,
        CreatedBy INT NULL,
        CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
        ModifiedBy INT NULL,
        ModifiedDate DATETIME NULL
    );
    CREATE INDEX IX_tblRogersInvoiceUPSLost_UserId ON tblRogersInvoiceUPSLost(UserId);
END;

-- 7. tblRogersInvoiceUPSLostUSER (Replicates tblUPSLostUSER)
IF OBJECT_ID('tblRogersInvoiceUPSLostUSER', 'U') IS NULL
BEGIN
    CREATE TABLE tblRogersInvoiceUPSLostUSER (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        UserId INT NOT NULL,
        Invoice VARCHAR(50) NULL,
        InvoiceDate DATETIME NULL,
        OrderDate DATETIME NULL,
        OriginalInvoice VARCHAR(255) NULL,
        CustName VARCHAR(255) NULL,
        Territory VARCHAR(255) NULL,
        WebOrderID VARCHAR(255) NULL,
        CellPhoneNo VARCHAR(255) NULL,
        Qty FLOAT NULL,
        PartNumber VARCHAR(50) NULL,
        FreeAccessory VARCHAR(255) NULL,
        IMEIESN VARCHAR(255) NULL,
        CostPrice FLOAT NULL,
        AccessoryCost FLOAT NULL,
        TotalBeforeTaxes FLOAT NULL,
        HST FLOAT NULL,
        TotalClaim FLOAT NULL,
        Courier VARCHAR(255) NULL,
        Claim VARCHAR(255) NULL,
        [Group] VARCHAR(255) NULL,
        OutstandingAR DECIMAL(18,2) NULL,
        NetIMEIReceiveCost DECIMAL(18,2) NULL,
        NetPriceProtection DECIMAL(18,2) NULL,
        NetCost DECIMAL(18,2) NULL,
        CreatedBy INT NULL,
        CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
        ModifiedBy INT NULL,
        ModifiedDate DATETIME NULL
    );
    CREATE INDEX IX_tblRogersInvoiceUPSLostUSER_UserId ON tblRogersInvoiceUPSLostUSER(UserId);
END;

-- 8. tblRogersInvoiceTempReturnsValidation (Replicates tblTempReturnsValidation)
IF OBJECT_ID('tblRogersInvoiceTempReturnsValidation', 'U') IS NULL
BEGIN
    CREATE TABLE tblRogersInvoiceTempReturnsValidation (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        UserId INT NOT NULL,
        ChannelName VARCHAR(255) NULL,
        PaymentMethod VARCHAR(255) NULL,
        Type VARCHAR(255) NULL,
        Invoice VARCHAR(255) NULL,
        InvoiceDate DATETIME NULL,
        CustTerritory VARCHAR(255) NULL,
        CellPhoneNo VARCHAR(255) NULL,
        WebOrderID VARCHAR(255) NULL,
        Qty FLOAT NULL,
        PartNumber VARCHAR(255) NULL,
        FreeAccessory VARCHAR(255) NULL,
        IMEIESN VARCHAR(255) NULL,
        CostPrice FLOAT NULL,
        SellPrice FLOAT NULL,
        TopUpOwing FLOAT NULL,
        AccessoryCost FLOAT NULL,
        AccessoryPrice FLOAT NULL,
        [TopUp Acc] FLOAT NULL,
        TopUpTotal FLOAT NULL,
        ARAmount FLOAT NULL,
        HDWChargeToCustomer FLOAT NULL,
        [True HDW TopUp] FLOAT NULL,
        ACCChargeToCx FLOAT NULL,
        AccMargin FLOAT NULL,
        [Group] VARCHAR(255) NULL,
        Source VARCHAR(255) NULL,
        ChannelName2 VARCHAR(255) NULL,
        PaymentMethod2 VARCHAR(255) NULL,
        Type2 VARCHAR(255) NULL,
        Invoice2 VARCHAR(255) NULL,
        InvoiceDate2 DATETIME NULL,
        CustTerritory2 VARCHAR(255) NULL,
        CellPhoneNo2 VARCHAR(255) NULL,
        WebOrderID2 VARCHAR(255) NULL,
        Qty2 FLOAT NULL,
        PartNumber2 VARCHAR(255) NULL,
        FreeAccessory2 VARCHAR(255) NULL,
        IMEIESN2 VARCHAR(255) NULL,
        CostPrice2 FLOAT NULL,
        SellPrice2 FLOAT NULL,
        TopUpOwing2 FLOAT NULL,
        AccessoryCost2 FLOAT NULL,
        AccessoryPrice2 FLOAT NULL,
        [TopUp Acc2] FLOAT NULL,
        TopUpTotal2 FLOAT NULL,
        ARAmount2 FLOAT NULL,
        HDWChargeToCustomer2 FLOAT NULL,
        [True HDW TopUp2] FLOAT NULL,
        ACCChargeToCx2 FLOAT NULL,
        AccMargin2 FLOAT NULL,
        Group2 VARCHAR(255) NULL,
        CreatedBy INT NULL,
        CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
        ModifiedBy INT NULL,
        ModifiedDate DATETIME NULL
    );
    CREATE INDEX IX_tblRogersInvoiceTempReturnsValidation_UserId ON tblRogersInvoiceTempReturnsValidation(UserId);
END;

-- 9. tblRogersInvoiceAcquisitionOutput (Replicates AcquisitionOutput)
IF OBJECT_ID('tblRogersInvoiceAcquisitionOutput', 'U') IS NULL
BEGIN
    CREATE TABLE tblRogersInvoiceAcquisitionOutput (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        UserId INT NOT NULL,
        ChannelName VARCHAR(255) NULL,
        PaymentMethod VARCHAR(255) NULL,
        Type VARCHAR(255) NULL,
        Invoice VARCHAR(255) NULL,
        InvoiceDate DATETIME NULL,
        OrderDate DATETIME NULL,
        CustName VARCHAR(255) NULL,
        CustTerritory VARCHAR(255) NULL,
        DealerCode VARCHAR(255) NULL,
        MSD VARCHAR(255) NULL,
        UserName VARCHAR(255) NULL,
        CellPhoneNo VARCHAR(255) NULL,
        PortedCTN VARCHAR(255) NULL,
        VoicePlan VARCHAR(255) NULL,
        DataPlan VARCHAR(255) NULL,
        WebOrderID VARCHAR(255) NULL,
        Type2 VARCHAR(255) NULL,
        Qty FLOAT NULL,
        PartNumber VARCHAR(255) NULL,
        FreeAccessory VARCHAR(255) NULL,
        IMEIESN VARCHAR(255) NULL,
        CostPrice FLOAT NULL,
        SellPrice FLOAT NULL,
        TopUpOwing FLOAT NULL,
        AccessoryCost FLOAT NULL,
        AccessoryPrice FLOAT NULL,
        [TopUp Acc] FLOAT NULL,
        TopUpTotal FLOAT NULL,
        Fee FLOAT NULL,
        FeeCount FLOAT NULL,
        ARAmount FLOAT NULL,
        [RV-UEValue] DECIMAL(18,2) NULL,
        HDWChargeToCustomer FLOAT NULL,
        [HDWRV-UEValue] DECIMAL(18,2) NULL,
        [True HDW TopUp] FLOAT NULL,
        HDWMargin DECIMAL(18,2) NULL,
        ACCChargeToCx FLOAT NULL,
        AccMargin FLOAT NULL,
        FeePayback FLOAT NULL,
        DealerHDWMargin DECIMAL(18,2) NULL,
        DealerACCMargin DECIMAL(18,2) NULL,
        [Group] VARCHAR(255) NULL,
        AccSellingPrice DECIMAL(18,2) NULL,
        SalesBeforeTax FLOAT NULL,
        [GST-HST] FLOAT NULL,
        [PST-QST] FLOAT NULL,
        M2MOrderID VARCHAR(255) NULL,
        ReturnClassification VARCHAR(255) NULL,
        Comments VARCHAR(255) NULL,
        RogersHWMarginShare DECIMAL(18,2) NULL,
        RogersACCMarginShare DECIMAL(18,2) NULL,
        RateTierTransactionCount FLOAT NULL,
        AccSeq INT NULL,
        RDAccUnitCost FLOAT NULL,
        RDAccExtendedCost FLOAT NULL,
        Term VARCHAR(255) NULL,
        AccessoryType VARCHAR(255) NULL,
        BAN VARCHAR(255) NULL,
        AgentName VARCHAR(255) NULL,
        AgentEmail VARCHAR(255) NULL,
        AgentContactNumber VARCHAR(255) NULL,
        BVReceiptCost DECIMAL(18,2) NULL,
        IMEIReceiveAppCost DECIMAL(18,2) NULL,
        NetPriceProtection DECIMAL(18,2) NULL,
        NetIMEIReceiveAppCost DECIMAL(18,2) NULL,
        ReceiptDate1 DATETIME NULL, Invoice1 VARCHAR(255) NULL, Qty1 INT NULL, Cost1 FLOAT NULL,
        ReceiptDate2 DATETIME NULL, Invoice2 VARCHAR(255) NULL, Qty2 INT NULL, Cost2 FLOAT NULL,
        ReceiptDate3 DATETIME NULL, Invoice3 VARCHAR(255) NULL, Qty3 INT NULL, Cost3 FLOAT NULL,
        ReceiptDate4 DATETIME NULL, Invoice4 VARCHAR(255) NULL, Qty4 INT NULL, Cost4 FLOAT NULL,
        ReceiptDate5 DATETIME NULL, Invoice5 VARCHAR(255) NULL, Qty5 INT NULL, Cost5 FLOAT NULL,
        ReceiptDate6 DATETIME NULL, Invoice6 VARCHAR(255) NULL, Qty6 INT NULL, Cost6 FLOAT NULL,
        ReceiptDate7 DATETIME NULL, Invoice7 VARCHAR(255) NULL, Qty7 INT NULL, Cost7 FLOAT NULL,
        BVReceiptNo VARCHAR(255) NULL,
        BVReceiptNoInt INT NULL,
        BVReceiptQty INT NULL,
        BVReceiptCostAcc FLOAT NULL,
        BVReceiptDate DATETIME NULL,
        RogersInvoiceCost FLOAT NULL,
        DeviceOfferTypeID INT NULL,
        ShipToProvince VARCHAR(255) NULL,
        GSTRate FLOAT NULL,
        PSTRate FLOAT NULL,
        OriginalInvoice VARCHAR(255) NULL,
        TaxFlag1 VARCHAR(255) NULL,
        TaxFlag2 VARCHAR(255) NULL,
        RDType VARCHAR(255) NULL,
        PPOverpayment DECIMAL(18,2) NULL,
        CreatedBy INT NULL,
        CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
        ModifiedBy INT NULL,
        ModifiedDate DATETIME NULL
    );
    CREATE INDEX IX_tblRogersInvoiceAcquisitionOutput_UserId ON tblRogersInvoiceAcquisitionOutput(UserId);
    CREATE INDEX IX_tblRogersInvoiceAcquisitionOutput_Invoice ON tblRogersInvoiceAcquisitionOutput(Invoice);
END;

-- 10. tblRogersInvoiceAcquisitionOutputUSER (Replicates AcquisitionOutputUSER)
IF OBJECT_ID('tblRogersInvoiceAcquisitionOutputUSER', 'U') IS NULL
BEGIN
    CREATE TABLE tblRogersInvoiceAcquisitionOutputUSER (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        UserId INT NOT NULL,
        ChannelName VARCHAR(255) NULL,
        PaymentMethod VARCHAR(255) NULL,
        Type VARCHAR(255) NULL,
        Invoice VARCHAR(255) NULL,
        InvoiceDate DATETIME NULL,
        OrderDate DATETIME NULL,
        CustName VARCHAR(255) NULL,
        CustTerritory VARCHAR(255) NULL,
        DealerCode VARCHAR(255) NULL,
        MSD VARCHAR(255) NULL,
        UserName VARCHAR(255) NULL,
        CellPhoneNo VARCHAR(255) NULL,
        PortedCTN VARCHAR(255) NULL,
        VoicePlan VARCHAR(255) NULL,
        DataPlan VARCHAR(255) NULL,
        WebOrderID VARCHAR(255) NULL,
        Type2 VARCHAR(255) NULL,
        Qty FLOAT NULL,
        PartNumber VARCHAR(255) NULL,
        PartNumberDescription VARCHAR(255) NULL,
        IMEIESN VARCHAR(255) NULL,
        HdwCost FLOAT NULL,
        HdwSellPrice FLOAT NULL,
        TopUpHdw FLOAT NULL,
        AccessoryCost FLOAT NULL,
        AccessoryPrice FLOAT NULL,
        [TopUp Acc] FLOAT NULL,
        TopUpTotal FLOAT NULL,
        Fee FLOAT NULL,
        FeePayback FLOAT NULL,
        FeeCount FLOAT NULL,
        ARAmount FLOAT NULL,
        [RV-UEValue] DECIMAL(18,2) NULL,
        HDWChargeToCustomer FLOAT NULL,
        [HDWRV-UEValue] DECIMAL(18,2) NULL,
        [True HDW TopUp] FLOAT NULL,
        ACCChargeToCx FLOAT NULL,
        AccMargin FLOAT NULL,
        HDWMargin FLOAT NULL,
        [Group] VARCHAR(255) NULL,
        ShipToProvince VARCHAR(255) NULL,
        SalesBeforeTax FLOAT NULL,
        [GST-HST] FLOAT NULL,
        [PST-QST] FLOAT NULL,
        Total FLOAT NULL,
        R4BOrderID VARCHAR(255) NULL,
        ReturnClassification VARCHAR(255) NULL,
        RateTierTransactionCount FLOAT NULL,
        Comments VARCHAR(255) NULL,
        AccSeq INT NULL,
        RDAccUnitCost FLOAT NULL,
        RDAccExtendedCost FLOAT NULL,
        AccessoryType VARCHAR(255) NULL,
        BAN VARCHAR(255) NULL,
        AgentName VARCHAR(255) NULL,
        AgentEmail VARCHAR(255) NULL,
        AgentContactNumber VARCHAR(255) NULL,
        RogersHWMarginShare DECIMAL(18,2) NULL,
        RogersACCMarginShare DECIMAL(18,2) NULL,
        Term VARCHAR(255) NULL,
        BVReceiptCost DECIMAL(18,2) NULL,
        IMEIReceiveAppCost DECIMAL(18,2) NULL,
        NetPriceProtection DECIMAL(18,2) NULL,
        NetIMEIReceiveAppCost DECIMAL(18,2) NULL,
        ReceiptDate1 DATETIME NULL, Invoice1 VARCHAR(255) NULL, Qty1 INT NULL, Cost1 FLOAT NULL,
        ReceiptDate2 DATETIME NULL, Invoice2 VARCHAR(255) NULL, Qty2 INT NULL, Cost2 FLOAT NULL,
        ReceiptDate3 DATETIME NULL, Invoice3 VARCHAR(255) NULL, Qty3 INT NULL, Cost3 FLOAT NULL,
        BVReceiptNo VARCHAR(255) NULL,
        BVReceiptNoInt INT NULL,
        BVReceiptQty INT NULL,
        BVReceiptCostAcc FLOAT NULL,
        BVReceiptDate DATETIME NULL,
        RogersInvoiceCost FLOAT NULL,
        DeviceOfferTypeID INT NULL,
        DealerHDWMargin DECIMAL(18,2) NULL,
        DealerACCMargin DECIMAL(18,2) NULL,
        RDType VARCHAR(255) NULL,
        PPOverpayment DECIMAL(18,2) NULL,
        CreatedBy INT NULL,
        CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
        ModifiedBy INT NULL,
        ModifiedDate DATETIME NULL
    );
    CREATE INDEX IX_tblRogersInvoiceAcquisitionOutputUSER_UserId ON tblRogersInvoiceAcquisitionOutputUSER(UserId);
END;

-- 11. tblRogersInvoiceAcquisitionARUSER (Replicates tblAcquisitionARUSER)
IF OBJECT_ID('tblRogersInvoiceAcquisitionARUSER', 'U') IS NULL
BEGIN
    CREATE TABLE tblRogersInvoiceAcquisitionARUSER (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        UserId INT NOT NULL,
        ChannelName VARCHAR(255) NULL,
        PaymentMethod VARCHAR(255) NULL,
        Type VARCHAR(255) NULL,
        Invoice VARCHAR(50) NULL,
        InvoiceDate DATETIME NULL,
        OrderDate DATETIME NULL,
        CustName VARCHAR(255) NULL,
        CustTerritory VARCHAR(50) NULL,
        DealerCode VARCHAR(255) NULL,
        MSD VARCHAR(255) NULL,
        UserName VARCHAR(50) NULL,
        CellPhoneNo VARCHAR(255) NULL,
        PortedCTN VARCHAR(255) NULL,
        VoicePlan VARCHAR(255) NULL,
        DataPlan VARCHAR(255) NULL,
        WebOrderID VARCHAR(255) NULL,
        Type2 VARCHAR(255) NULL,
        Qty FLOAT NULL,
        PartNumber VARCHAR(50) NULL,
        PartNumberDescription VARCHAR(255) NULL,
        IMEIESN VARCHAR(255) NULL,
        HdwCost FLOAT NULL,
        HdwSellPrice FLOAT NULL,
        TopUpHdw FLOAT NULL,
        [Topup Acc] FLOAT NULL,
        TopUpTotal FLOAT NULL,
        AccessoryPrice FLOAT NULL,
        Fee FLOAT NULL,
        FeeCount INT NULL,
        GST FLOAT NULL,
        PST FLOAT NULL,
        HST FLOAT NULL,
        QST FLOAT NULL,
        ARAmount FLOAT NULL,
        HDWChargeToCustomer FLOAT NULL,
        [True HDW TopUp] VARCHAR(255) NULL,
        SCOA VARCHAR(50) NULL,
        ShipToProvince VARCHAR(10) NULL,
        CreatedBy INT NULL,
        CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
        ModifiedBy INT NULL,
        ModifiedDate DATETIME NULL
    );
    CREATE INDEX IX_tblRogersInvoiceAcquisitionARUSER_UserId ON tblRogersInvoiceAcquisitionARUSER(UserId);
END;

-- 12. tblRogersInvoiceAcquisitionDetailUSER (Replicates tblAcquisitionDetailUSER)
IF OBJECT_ID('tblRogersInvoiceAcquisitionDetailUSER', 'U') IS NULL
BEGIN
    CREATE TABLE tblRogersInvoiceAcquisitionDetailUSER (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        UserId INT NOT NULL,
        ChannelName VARCHAR(255) NULL,
        PaymentMethod VARCHAR(255) NULL,
        Type VARCHAR(255) NULL,
        Invoice VARCHAR(50) NULL,
        BVLineNo INT NULL,
        RecNoDetail INT NULL,
        InvoiceDate DATETIME NULL,
        OrderDate DATETIME NULL,
        CustName VARCHAR(255) NULL,
        CustTerritory VARCHAR(50) NULL,
        DealerCode VARCHAR(255) NULL,
        CellPhoneNo VARCHAR(255) NULL,
        WebOrderID VARCHAR(255) NULL,
        Type2 VARCHAR(255) NULL,
        FreeAccessory VARCHAR(255) NULL,
        [Topup Acc] FLOAT NULL,
        AccessoryCost FLOAT NULL,
        AccessoryPrice FLOAT NULL,
        AccCurrentCostTotal FLOAT NULL,
        AccSRPTotal FLOAT NULL,
        AccSRP17Total FLOAT NULL,
        AccSRP25Total FLOAT NULL,
        AccSRP50Total FLOAT NULL,
        ACCSellingPrice FLOAT NULL,
        CODE VARCHAR(50) NULL,
        Description VARCHAR(255) NULL,
        ProdCode VARCHAR(50) NULL,
        Qty FLOAT NULL,
        BVCost FLOAT NULL,
        BVCostExt FLOAT NULL,
        BVPrice FLOAT NULL,
        BVPriceExt FLOAT NULL,
        TopUpAmt FLOAT NULL,
        TopUpOrig FLOAT NULL,
        TopUpModify VARCHAR(10) NULL,
        CustPayExt FLOAT NULL,
        AccGroup VARCHAR(50) NULL,
        Margin VARCHAR(255) NULL,
        AccSRP FLOAT NULL,
        AccSRP17 FLOAT NULL,
        AccSRP25 FLOAT NULL,
        AccSRP50 FLOAT NULL,
        TopUpRecalc FLOAT NULL,
        MSD VARCHAR(255) NULL,
        UserName VARCHAR(255) NULL,
        VoicePlan VARCHAR(255) NULL,
        DataPlan VARCHAR(255) NULL,
        GSTRate FLOAT NULL,
        PSTRate FLOAT NULL,
        Fee FLOAT NULL,
        FeePayback FLOAT NULL,
        M2MOrderID VARCHAR(255) NULL,
        ReturnClassification VARCHAR(255) NULL,
        GSTFlag VARCHAR(255) NULL,
        PSTFlag VARCHAR(255) NULL,
        AdjustmentType VARCHAR(255) NULL,
        BVReceiptNo VARCHAR(255) NULL,
        BVReceiptNoInt INT NULL,
        BVReceiptQty INT NULL,
        BVReceiptCost FLOAT NULL,
        BVReceiptDate DATETIME NULL,
        RogersInvoiceCost FLOAT NULL,
        DeviceOfferTypeID INT NULL,
        ShipToProvince VARCHAR(255) NULL,
        OriginalInvoice VARCHAR(255) NULL,
        RDAccUnitCost FLOAT NULL,
        AccessoryType VARCHAR(255) NULL,
        RogersACCMarginShare DECIMAL(18,2) NULL,
        AccountNumber VARCHAR(255) NULL,
        AgentName VARCHAR(255) NULL,
        AgentEmail VARCHAR(255) NULL,
        AgentContactNumber VARCHAR(255) NULL,
        RDType VARCHAR(255) NULL,
        CreatedBy INT NULL,
        CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
        ModifiedBy INT NULL,
        ModifiedDate DATETIME NULL
    );
    CREATE INDEX IX_tblRogersInvoiceAcquisitionDetailUSER_UserId ON tblRogersInvoiceAcquisitionDetailUSER(UserId);
END;
