-- SQL Script for Customer Sales Module Tables

CREATE TABLE tblCustomerGroups (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CustGroup NVARCHAR(100) NOT NULL,
    BVCustNo NVARCHAR(100) NOT NULL,
    GroupName NVARCHAR(255),
    BVName NVARCHAR(255),
    CreatedBy INT,
    CreatedDate DATETIME DEFAULT GETDATE(),
    ModifiedBy INT,
    ModifiedDate DATETIME
);

CREATE TABLE tblCustomerColumns (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CustomerGroup NVARCHAR(100) NOT NULL,
    FieldName NVARCHAR(100) NOT NULL,
    Label NVARCHAR(100),
    Include BIT NOT NULL DEFAULT 1,
    Sequence INT NOT NULL DEFAULT 0,
    SummaryType NVARCHAR(50),
    FormatString NVARCHAR(100),
    Level INT,
    CreatedBy INT,
    CreatedDate DATETIME DEFAULT GETDATE(),
    ModifiedBy INT,
    ModifiedDate DATETIME
);

CREATE TABLE tblCustomerSalesOutput (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    WebOrderID NVARCHAR(100),
    Invoice NVARCHAR(100),
    InvoiceDate DATETIME,
    VoicePlanDescription NVARCHAR(MAX),
    DataPlanDescription NVARCHAR(MAX),
    CellPhoneNo NVARCHAR(50),
    UserName NVARCHAR(255),
    PONo NVARCHAR(255),
    CostBudgetCode NVARCHAR(100),
    PartNumber NVARCHAR(100),
    HardwareDescription NVARCHAR(MAX),
    HDWQty INT,
    IMEIESN NVARCHAR(100),
    AccParts NVARCHAR(MAX),
    AccessoryDescription NVARCHAR(MAX),
    AccQtys NVARCHAR(MAX),
    ShipToProvince NVARCHAR(50),
    InvoiceNet DECIMAL(18,2),
    InvoiceShipping DECIMAL(18,2),
    InvoiceTaxes DECIMAL(18,2),
    InvoiceTotal DECIMAL(18,2),
    CustGroup NVARCHAR(100),
    CustNO NVARCHAR(100),
    TypeOfService NVARCHAR(100),
    PinNumber NVARCHAR(100),
    HSTGST DECIMAL(18,2),
    PSTQST DECIMAL(18,2),
    MSDCode NVARCHAR(100),
    CustomerName NVARCHAR(255),
    Territory NVARCHAR(100),
    AccountCode NVARCHAR(100),
    AuthorizedDepartment NVARCHAR(100),
    ShipToAddress NVARCHAR(MAX),
    ShipToStreetAddress NVARCHAR(MAX),
    ShipToCity NVARCHAR(255),
    ShipToPostal NVARCHAR(50),
    GSTRate DECIMAL(18,2),
    PSTRate DECIMAL(18,2),
    GSTFlag NVARCHAR(10),
    PSTFlag NVARCHAR(10),
    Tax1Code INT,
    Tax2Code INT,
    PortedCTN NVARCHAR(50),
    BulkOrderID NVARCHAR(100),
    HardwareCharge DECIMAL(18,2),
    AccessoryCharge DECIMAL(18,2),
    ARStatus NVARCHAR(100),
    UserPayAmount DECIMAL(18,2),
    UserPayMethod NVARCHAR(100),
    Balance DECIMAL(18,2),
    UserId INT NOT NULL,
    CreatedBy INT,
    CreatedDate DATETIME DEFAULT GETDATE(),
    ModifiedBy INT,
    ModifiedDate DATETIME
);
